---
hero_image: images/banner.png
listed: true
ingredient: false
copyedit: false
title: Sneeuwballen gevecht
description: Maak een spel waarin je sneeuwballen naar een doel moet gooien
version: 4
last_tested: 2018-04-11
steps:
- title: Inleiding
- title: Een sneeuwbal maken
- title: Een sneeuwbal gooien
  completion:
  - engaged
- title: Realistische beweging
- title: Het doelwit
  completion:
  - internal
- title: 'Uitdaging: verbeter je spel!'
  challenge: true
- title: Wat kun je verder nog doen?
