---
hero_image: images/banner.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Snowball fight
description: Make a game in which you have to throw snowballs at a target
original_url: https://codeclubprojects.org/en-GB/scratch/snowball-fight
interests: outdoors
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: Making a snowball
- title: Throwing a snowball
- title: Realistic movement
- title: The target
- title: "Challenge: improve your game!"