---
hero_image: images/banner.png
listed: true
ingredient: false
copyedit: false
title: Lucha de bolas de nieve
description: Haz un juego en el que tengas que lanzar bolas de nieve a un objetivo
version: 4
last_tested: 2018-04-11
steps:
- title: Introducción
- title: Haciendo una bola de nieve
- title: Lanzando una bola de nieve
  completion:
  - engaged
- title: Movimiento realista
- title: El objetivo
  completion:
  - internal
- title: 'Desafío: ¡Mejora tu juego!'
  challenge: true