---
hero_image: images/banner.png
listed: true
ingredient: false
copyedit: false
title: Bataille de boules de neige
description: Crée un jeu dans lequel tu dois lancer des boules de neige sur une cible
version: 4
last_tested: 2018-04-11
steps:
- title: Introduction
- title: Faire une boule de neige
- title: Lancer une boule de neige
  completion:
  - engaged
- title: Mouvement réaliste
- title: La cible
  completion:
  - internal
- title: 'Défi: améliore ton jeu!'
  challenge: true
- title: Et ensuite?
